schema_version = "1.0.0"

id = "playback_ranges"
version = "1.0.5"
name = "Playback Ranges"
tagline = "Playback Ranges"
maintainer = "todashuta <toda.shuta@gmail.com>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "/make.cmd",
]
